# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-29 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_remove_product_supply_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
